FIX: `exec_with_gems` doesn't work on macOS 10.15.
**Problems**

macOS 10.15 has Ruby 2.6, which includes Bundler.
Reported as issue #33.

**Solution**

Update `exec_with_gems` to support Ruby 2.6, also fixes deprecated
gems options, comments and checks Bundler is executable or not.

diff --git a/scripts/exec_with_gems b/scripts/exec_with_gems
--- a/scripts/exec_with_gems
+++ b/scripts/exec_with_gems
@@ -6,56 +6,75 @@ exec_with_gems() {
 
   local -r root_dir="$(cd -P "$(dirname "${BASH_SOURCE[0]}")/.."; pwd)"
 
-  # Use system Ruby always.
+  # Use system Ruby.
   local -r ruby_bin_path="/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/bin"
   if [[ ! -d "$ruby_bin_path" ]]; then
-    echo "No system ruby $ruby_bin_path found." >&2
+    echo "No system Ruby $ruby_bin_path found." >&2
     exit 1
   fi
 
+  # Use system Rubygems.
   local -r rubygems="$ruby_bin_path/gem"
+  if [[ ! -e $rubygems ]]; then
+    echo "No system rubygems $rubygems found." >&2
+    exit 1
+  fi
 
-  # Set GEM_HOME and GEM_PATH to isolate gems.
+  # Set `GEM_HOME` and `GEM_PATH` to isolate gems.
   export GEM_HOME="$root_dir/.gems"
   export GEM_PATH="$GEM_HOME"
   mkdir -p "$GEM_HOME"
 
-  # Use 1.x Bundler instead to support rubygems 2.x used by system Ruby.
-  local -r bundler_version="~> 1.17"
+  # Prior to Ruby 2.6, the system Ruby doesn't have Bundler.
+  local bundler="$ruby_bin_path/bundle"
+  if [[ ! -e $bundler ]]; then
+    # Use Bundler installed by Rubygems.
+    bundler="$GEM_HOME/bin/bundle"
 
-  # Install or update Bundler, if it's not present or not executable.
-  # Since bundler binstubs are installed with `--no-env-shebang` to use system ruby,
-  # in case macOS updated its `Ruby.framework`, the binstubs are no longer executable.
-  # Use `help` command to test if it's runnable or not.
-  ("$rubygems" list --norc -i bundler -v "$bundler_version" > /dev/null) || {
-    echo "No bundler found in $GEM_HOME, install it..."
+    # Use 1.x Bundler instead to support Rubygems 2.x used by the system Ruby.
+    local -r bundler_version="~> 1.17"
 
-    # Install or update Bundler.
-    "$rubygems" install \
-      --norc \
-      --no-user-install \
-      --no-env-shebang \
-      --no-rdoc \
-      --no-ri \
-      --clear-sources \
-      --version "$bundler_version" \
-      bundler || {
-      echo "Fail to install bundler." >&2
-      exit 1
-    }
+    local is_bundler_executable
+    if [[ -e $bundler ]] && "$bundler" help >/dev/null 2>&1; then
+      is_bundler_executable=1
+    fi
+    readonly is_bundler_executable
 
-    # Cleanup all previous versions of Bundler.
-    "$rubygems" cleanup bundler
-  }
+    local is_bundler_updated
+    if "$rubygems" list --norc -i bundler -v "$bundler_version" > /dev/null 2>&1; then
+      is_bundler_updated=1
+    fi
+    readonly is_bundler_updated
 
-  # Install dependency gems using installed Bundler.
-  # All dependencies are managed by Bundler `Gemfile`,
-  # except Bundler itself.
-  ("$GEM_HOME/bin/bundle" check > /dev/null) || {
+    if ! (( is_bundler_executable )) || ! (( is_bundler_updated )); then
+      echo "No bundler found in $GEM_HOME, install it..."
+
+      # Install or update Bundler.
+      "$rubygems" install \
+        --norc \
+        --no-document \
+        --no-env-shebang \
+        --no-user-install \
+        --clear-sources \
+        --version "$bundler_version" \
+        bundler || {
+        echo "Fail to install bundler." >&2
+        exit 1
+      }
+
+      # Cleanup all previous versions of Bundler.
+      "$rubygems" cleanup bundler
+    fi
+  fi
+  readonly bundler
+
+  # Install dependency gems using Bundler.
+  # All dependencies are managed by Bundler `Gemfile`, except Bundler itself.
+  if ! "$bundler" check > /dev/null; then
     echo "Update gems dependencies..."
 
     # Install or update gems.
-    "$GEM_HOME/bin/bundle" install \
+    "$bundler" install \
       --gemfile "$root_dir/Gemfile" \
       --without development || {
       echo "Fail to bundle install." >&2
@@ -63,8 +82,8 @@ exec_with_gems() {
     }
 
     # Cleanup all previous version of gems.
-    "$GEM_HOME/bin/bundle" clean --force
-  }
+    "$bundler" clean --force
+  fi
 
   # Set gems bin path to PATH.
   export PATH="$ruby_bin_path:$GEM_HOME/bin:$PATH"
